name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Export Resume
        run: .\Export-Resume.ps1 -Name jbeeson -Destination $env:RUNNER_TEMP\thisJUSTin816

      - name: Publish Resume
        uses: actions/upload-artifact@v2.3.0
        with:
          name: jbeeson-resume
          path: ${{ env.RUNNER_TEMP }}\thisJUSTin816
