name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Export Resume
        run: .\Export-Resume.ps1 -Name jbeeson

      - name: Publish Resume
        uses: actions/upload-artifact@v4
        with:
          name: jbeeson-resume
          path: |
            *.pdf
            *.txt
